/**
 * @file Config Editor Component
 * @description GUI-based configuration editor for local development only
 */

import React, { useState, useEffect, useCallback } from 'react';
import PropTypes from 'prop-types';
import styles from './configEditor.module.css';
import { hasConfigAccess } from '../../util/isLocal';
import config from '../../config';

/**
 * Parses GitHub username from URL
 * @param {string} url - GitHub URL
 * @returns {string} - Username or empty string
 */
function parseGithubUsername (url) {
  if (!url) return '';
  const match = url.match(/github\.com\/([^/]+)/);
  return match ? match[1] : '';
}

/**
 * Escapes single quotes in a string for use in single-quoted JavaScript strings
 * @param {string} str - String to escape
 * @returns {string} - Escaped string
 */
export function escapeString (str) {
  if (typeof str !== 'string') return str;
  // Escape single quotes and backslashes
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

/**
 * Formats an object for config output with proper indentation
 * @param {Object} obj - Object to format
 * @param {number} baseIndent - Base indentation level (spaces)
 * @returns {string} - Formatted string
 */
export function formatObject (obj, baseIndent = 2) {
  // Get the JSON representation
  const jsonStr = JSON.stringify(obj, null, 2)
    .replace(/"([^"]+)":/g, '$1:')
    .replace(/"/g, "'");

  const lines = jsonStr.split('\n');
  const baseSpaces = ' '.repeat(baseIndent);

  // First line is opening brace, subsequent lines need baseIndent added
  // but we need to preserve the relative indentation of nested content
  return lines
    .map((line, index) => {
      if (index === 0) {
        // Opening brace stays as is
        return line;
      }
      // For all other lines, add baseIndent spaces
      // The line already has its own indentation from JSON.stringify (2 spaces per level)
      // We need to add baseIndent to get the correct absolute position
      return baseSpaces + line;
    })
    .join('\n');
}

/**
 * Converts config object to JavaScript file content
 * @param {Object} configObj - Config object
 * @returns {string} - JavaScript file content
 */
export function configToJsContent (configObj) {
  const headersStr = formatObject(configObj.headers, 2);
  const linkStyleStr = formatObject(configObj.markdown.linkStyle, 4);
  const colorsStr = formatObject(configObj.colors, 2);

  return `/**
 * @author ${escapeString(configObj.name)}
 * @email ${escapeString(configObj.email)}
 * @create date ${new Date().toISOString().split('T')[0]}
 * @modify date ${new Date().toISOString().split('T')[0]}
 * @desc Blog Configuration - Generated by GUI Config Editor
 */
const config = {
  debug: ${configObj.debug},
  // github readme url
  readmeUrl: '${escapeString(configObj.readmeUrl)}',
  // blog title, on left top of the page
  title: '${escapeString(configObj.title)}',
  // author name
  name: '${escapeString(configObj.name)}',
  // social links, on bottom of the page
  social: {
    github: '${escapeString(configObj.social.github)}',
    linkedin: '${escapeString(configObj.social.linkedin)}'
  },
  email: '${escapeString(configObj.email)}',
  repo: '${escapeString(configObj.repo)}',
  resume_url: '${escapeString(configObj.resume_url)}',
  // default content shown on the main page, /src/articles/[config.default].md
  default: '${escapeString(configObj.default)}',
  headers: ${headersStr},
  // markdown settings
  markdown: {
    // set it false to disable markdown editor
    enable: ${configObj.markdown.enable},
    // set it true to enable loading animation in refreshing markdown preview.
    loading: ${configObj.markdown.loading},
    // delay time for refreshing markdown preview
    renderDelay: ${configObj.markdown.renderDelay},
    // tab size for markdown editor
    tabSize: ${configObj.markdown.tabSize},
    // the links in markdown does not have underlines, set it true to enable underline
    linkStyle: ${linkStyleStr}
  },
  themeChange: ${configObj.themeChange},
  colors: ${colorsStr}
}

export default config;
`;
}

/**
 * Initializes form state from existing config
 * @returns {Object} - Initial form state
 */
function getInitialFormState () {
  const githubUsername = parseGithubUsername(config.social?.github);

  // Preserve the actual headers array structure with all properties (type, customUrl)
  const headers = config.headers?.map(h => ({ ...h })) || [];

  // Calculate derived values for UI convenience
  const pages = {
    about: headers.some(h => h.title === 'About'),
    blog: headers.some(h => h.title === 'Blog'),
    projects: headers.some(h => h.title === 'Projects'),
    techstack: headers.some(h => h.title === 'Tech Stack'),
    links: headers.some(h => h.title === 'Links'),
    resume: headers.some(h => h.title === 'Resume')
  };

  return {
    blogTitle: config.title || '',
    authorName: config.name || '',
    email: config.email || '',
    githubUsername,
    linkedinUrl: config.social?.linkedin || '',
    repoUrl: config.repo || '',
    resumeUrl: config.resume_url || '',
    debug: config.debug || false,
    themeChange: config.themeChange !== false,
    // Preserve full headers array with type, customUrl, etc.
    headers,
    // UI convenience flags
    pages,
    markdownEnable: config.markdown?.enable !== false,
    markdownLoading: config.markdown?.loading || false,
    markdownRenderDelay: config.markdown?.renderDelay || 0,
    markdownTabSize: config.markdown?.tabSize || 2,
    markdownLinkUnderline: config.markdown?.linkStyle?.textDecoration === 'underline',
    markdownLinkColor: config.markdown?.linkStyle?.color || '#0077ff'
  };
}

/**
 * Generates config object from form state
 * Preserves all header properties including type and customUrl
 * @param {Object} formState - Current form state
 * @returns {Object} - Config object
 */
export function generateConfigFromState (formState) {
  const githubUrl = formState.githubUsername
    ? `https://github.com/${formState.githubUsername}`
    : '';

  // Build headers array preserving existing header objects when available
  // This preserves customUrl, type, and any other properties
  const headers = [];

  // Helper to find existing header or create new one
  const addHeader = (title, defaultType = 'article', defaultCustomUrl = null) => {
    const existing = formState.headers.find(h => h.title === title);
    if (existing) {
      // Preserve the existing header with all its properties
      headers.push({ ...existing });
    } else {
      // Create new header
      const header = { title, type: defaultType };
      if (defaultCustomUrl) {
        header.customUrl = defaultCustomUrl;
      }
      headers.push(header);
    }
  };

  // Add headers in order based on page toggles
  if (formState.pages.about) addHeader('About', 'article');
  if (formState.pages.techstack) addHeader('Tech Stack', 'article', 'TechStack');
  if (formState.pages.blog) addHeader('Blog', 'article');
  if (formState.pages.projects) addHeader('Projects', 'article', 'Projects/Project');

  // Always add MarkDown if markdown is enabled
  if (formState.markdownEnable) {
    addHeader('MarkDown', 'article');
  }

  if (formState.pages.resume) {
    // For Resume, use existing header with its customUrl (link URL) if available
    const existingResume = formState.headers.find(h => h.title === 'Resume');
    if (existingResume && existingResume.customUrl) {
      headers.push({ ...existingResume });
    } else if (formState.resumeUrl) {
      headers.push({
        title: 'Resume',
        type: 'link',
        customUrl: formState.resumeUrl
      });
    }
  }

  if (formState.pages.links) addHeader('Links', 'article');

  return {
    debug: formState.debug,
    readmeUrl: formState.repoUrl ? `${formState.repoUrl}/blob/main/README.md` : '',
    title: formState.blogTitle,
    name: formState.authorName,
    social: {
      github: githubUrl,
      linkedin: formState.linkedinUrl
    },
    email: formState.email,
    repo: formState.repoUrl,
    resume_url: formState.resumeUrl,
    default: 'About',
    headers,
    markdown: {
      enable: formState.markdownEnable,
      loading: formState.markdownLoading,
      renderDelay: parseInt(formState.markdownRenderDelay, 10) || 0,
      tabSize: parseInt(formState.markdownTabSize, 10) || 2,
      linkStyle: {
        textDecoration: formState.markdownLinkUnderline ? 'underline' : 'none',
        color: formState.markdownLinkColor
      }
    },
    themeChange: formState.themeChange,
    // Include colors from original config (preserved for components that use them)
    colors: config.colors || {
      light: { background: '#ffffff', foreground: '#feb272', gray: '#212529' },
      dark: { background: '#212020', foreground: '#653208', gray: '#a9a9b3' }
    }
  };
}

// Tab components
const TabGeneral = ({ formState, setFormState }) => (
  <div className={styles['tab-content']}>
    <h2>General Settings</h2>

    <div className={styles['form-group']}>
      <label htmlFor="blogTitle">Blog Title *</label>
      <input
        type="text"
        id="blogTitle"
        value={formState.blogTitle}
        onChange={(e) => setFormState(prev => ({ ...prev, blogTitle: e.target.value }))}
        placeholder="My Awesome Blog"
        required
      />
      <small>Displayed in the header and browser tab</small>
    </div>

    <div className={styles['form-group']}>
      <label htmlFor="authorName">Author Name *</label>
      <input
        type="text"
        id="authorName"
        value={formState.authorName}
        onChange={(e) => setFormState(prev => ({ ...prev, authorName: e.target.value }))}
        placeholder="John Doe"
        required
      />
    </div>

    <div className={styles['form-group']}>
      <label htmlFor="email">Email Address</label>
      <input
        type="email"
        id="email"
        value={formState.email}
        onChange={(e) => setFormState(prev => ({ ...prev, email: e.target.value }))}
        placeholder="john@example.com"
      />
    </div>

    <div className={styles['form-group']}>
      <label htmlFor="repoUrl">GitHub Repository URL</label>
      <input
        type="url"
        id="repoUrl"
        value={formState.repoUrl}
        onChange={(e) => setFormState(prev => ({ ...prev, repoUrl: e.target.value }))}
        placeholder="https://github.com/username/repo"
      />
      <small>Used to generate README and issue links</small>
    </div>
  </div>
);

const TabSocial = ({ formState, setFormState }) => (
  <div className={styles['tab-content']}>
    <h2>Social Links</h2>

    <div className={styles['form-group']}>
      <label htmlFor="githubUsername">GitHub Username</label>
      <input
        type="text"
        id="githubUsername"
        value={formState.githubUsername}
        onChange={(e) => setFormState(prev => ({ ...prev, githubUsername: e.target.value }))}
        placeholder="username"
      />
    </div>

    <div className={styles['form-group']}>
      <label htmlFor="linkedinUrl">LinkedIn URL</label>
      <input
        type="url"
        id="linkedinUrl"
        value={formState.linkedinUrl}
        onChange={(e) => setFormState(prev => ({ ...prev, linkedinUrl: e.target.value }))}
        placeholder="https://linkedin.com/in/username"
      />
    </div>

    <div className={styles['form-group']}>
      <label htmlFor="resumeUrl">Resume/CV URL</label>
      <input
        type="url"
        id="resumeUrl"
        value={formState.resumeUrl}
        onChange={(e) => setFormState(prev => ({ ...prev, resumeUrl: e.target.value }))}
        placeholder="https://example.com/resume.pdf"
      />
      <small>Add a Resume link to navigation. Must be a full URL (http:// or https://)</small>
    </div>
  </div>
);

const TabPages = ({ formState, setFormState }) => {
  const togglePage = (page) => {
    setFormState(prev => ({
      ...prev,
      pages: { ...prev.pages, [page]: !prev.pages[page] }
    }));
  };

  return (
    <div className={styles['tab-content']}>
      <h2>Page Configuration</h2>
      <p>Select which pages to include in your navigation:</p>

      <div className={styles['form-group']}>
        <div className={styles['checkbox-group']}>
          <label>
            <input
              type="checkbox"
              checked={formState.pages.about}
              onChange={() => togglePage('about')}
            />
            About (Home page)
          </label>
        </div>

        <div className={styles['checkbox-group']}>
          <label>
            <input
              type="checkbox"
              checked={formState.pages.blog}
              onChange={() => togglePage('blog')}
            />
            Blog
          </label>
        </div>

        <div className={styles['checkbox-group']}>
          <label>
            <input
              type="checkbox"
              checked={formState.pages.projects}
              onChange={() => togglePage('projects')}
            />
            Projects (custom path: Projects/Project)
          </label>
        </div>

        <div className={styles['checkbox-group']}>
          <label>
            <input
              type="checkbox"
              checked={formState.pages.techstack}
              onChange={() => togglePage('techstack')}
            />
            Tech Stack (custom path: TechStack)
          </label>
        </div>

        <div className={styles['checkbox-group']}>
          <label>
            <input
              type="checkbox"
              checked={formState.pages.links}
              onChange={() => togglePage('links')}
            />
            Links
          </label>
        </div>

        <div className={styles['checkbox-group']}>
          <label>
            <input
              type="checkbox"
              checked={formState.pages.resume}
              onChange={() => togglePage('resume')}
            />
            Resume Link (external link, requires Resume URL)
          </label>
        </div>
      </div>

      <div className={styles['form-group']}>
        <div className={styles['checkbox-group']}>
          <label>
            <input
              type="checkbox"
              checked={formState.markdownEnable}
              onChange={() => setFormState(prev => ({ ...prev, markdownEnable: !prev.markdownEnable }))}
            />
            Enable Markdown Editor (adds MarkDown page)
          </label>
          <small>The Markdown editor allows writing and previewing markdown</small>
        </div>
      </div>
    </div>
  );
};

const TabSettings = ({ formState, setFormState }) => (
  <div className={styles['tab-content']}>
    <h2>Settings</h2>

    <div className={styles['form-group']}>
      <div className={styles['checkbox-group']}>
        <label>
          <input
            type="checkbox"
            checked={formState.themeChange}
            onChange={() => setFormState(prev => ({ ...prev, themeChange: !prev.themeChange }))}
          />
          Enable Theme Switcher (Light/Dark mode toggle)
        </label>
      </div>
    </div>

    <div className={styles['form-group']}>
      <div className={styles['checkbox-group']}>
        <label>
          <input
            type="checkbox"
            checked={formState.debug}
            onChange={() => setFormState(prev => ({ ...prev, debug: !prev.debug }))}
          />
          Enable Debug Mode
        </label>
        <small>Shows debug messages in browser console</small>
      </div>
    </div>

    <h3>Markdown Editor Settings</h3>

    <div className={styles['form-group']}>
      <label htmlFor="markdownTabSize">Tab Size</label>
      <input
        type="number"
        id="markdownTabSize"
        value={formState.markdownTabSize}
        onChange={(e) => setFormState(prev => ({ ...prev, markdownTabSize: e.target.value }))}
        min="1"
        max="8"
      />
    </div>

    <div className={styles['form-group']}>
      <div className={styles['checkbox-group']}>
        <label>
          <input
            type="checkbox"
            checked={formState.markdownLinkUnderline}
            onChange={() => setFormState(prev => ({ ...prev, markdownLinkUnderline: !prev.markdownLinkUnderline }))}
          />
          Underline Links in Markdown Preview
        </label>
      </div>
    </div>

    <div className={styles['form-group']}>
      <label htmlFor="markdownLinkColor">Link Color</label>
      <input
        type="color"
        id="markdownLinkColor"
        value={formState.markdownLinkColor}
        onChange={(e) => setFormState(prev => ({ ...prev, markdownLinkColor: e.target.value }))}
      />
    </div>
  </div>
);

TabGeneral.propTypes = {
  formState: PropTypes.object.isRequired,
  setFormState: PropTypes.func.isRequired
};

TabSocial.propTypes = {
  formState: PropTypes.object.isRequired,
  setFormState: PropTypes.func.isRequired
};

TabPages.propTypes = {
  formState: PropTypes.object.isRequired,
  setFormState: PropTypes.func.isRequired
};

TabSettings.propTypes = {
  formState: PropTypes.object.isRequired,
  setFormState: PropTypes.func.isRequired
};

// Export Modal Component
function ExportModal ({ configContent, onClose, onDownload, onCopy }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    onCopy();
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className={styles.modal} onClick={onClose}>
      <div className={styles['modal-content']} onClick={(e) => e.stopPropagation()}>
        <div className={styles['modal-header']}>
          <h2>Export Configuration</h2>
          <button className={styles['modal-close']} onClick={onClose}>
            &times;
          </button>
        </div>
        <div className={styles['modal-body']}>
          <div className={styles['export-actions']}>
            <button className={styles['btn-primary']} onClick={onDownload}>
              Download config.js
            </button>
            <button className={styles['btn-secondary']} onClick={handleCopy}>
              {copied ? 'Copied!' : 'Copy to Clipboard'}
            </button>
          </div>
          <div className={styles['export-preview']}>
            <code>
              <pre>{configContent}</pre>
            </code>
          </div>
          <p className={styles['access-note']}>
            Copy this content to your <code>src/config.js</code> file to apply the changes.
          </p>
        </div>
      </div>
    </div>
  );
}

ExportModal.propTypes = {
  configContent: PropTypes.string.isRequired,
  onClose: PropTypes.func.isRequired,
  onDownload: PropTypes.func.isRequired,
  onCopy: PropTypes.func.isRequired
};

// Main Config Editor Component
export default function ConfigEditor () {
  const [hasAccess, setHasAccess] = useState(null);
  const [activeTab, setActiveTab] = useState('general');
  const [formState, setFormState] = useState(getInitialFormState());
  const [showExport, setShowExport] = useState(false);

  useEffect(() => {
    setHasAccess(hasConfigAccess());
  }, []);

  const handleExport = useCallback(() => {
    setShowExport(true);
  }, []);

  const handleDownload = useCallback(() => {
    const newConfig = generateConfigFromState(formState);
    const content = configToJsContent(newConfig);
    const blob = new Blob([content], { type: 'application/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'config.js';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [formState]);

  const handleCopy = useCallback(() => {
    const newConfig = generateConfigFromState(formState);
    const content = configToJsContent(newConfig);
    navigator.clipboard.writeText(content);
  }, [formState]);

  const handleReset = useCallback(() => {
    if (window.confirm('Reset all settings to current saved values?')) {
      setFormState(getInitialFormState());
    }
  }, []);

  if (hasAccess === null) {
    return (
      <div className={styles.loading}>
        <p>Checking access...</p>
      </div>
    );
  }

  if (!hasAccess) {
    return (
      <div className={styles['access-denied']}>
        <div className={styles['access-denied-content']}>
          <h1>Access Denied</h1>
          <p>
            The configuration editor is only accessible from a local development environment.
          </p>
          <code className={styles['access-hint']}>npm start</code>
          <p className={styles['access-note']}>
            Visitors to your published blog cannot access this page.
          </p>
        </div>
      </div>
    );
  }

  const tabs = [
    { id: 'general', label: 'General', component: TabGeneral },
    { id: 'social', label: 'Social', component: TabSocial },
    { id: 'pages', label: 'Pages', component: TabPages },
    { id: 'settings', label: 'Settings', component: TabSettings }
  ];

  const ActiveComponent = tabs.find(t => t.id === activeTab)?.component || TabGeneral;

  return (
    <div className={styles['config-editor-container']}>
      <div className={styles['config-editor-header']}>
        <h1>Blog Configuration</h1>
        <p>Edit your blog settings. Changes will be exported as a config.js file.</p>
      </div>

      <div className={styles['config-editor-tabs']}>
        {tabs.map(tab => (
          <button
            key={tab.id}
            className={`${styles.tab} ${activeTab === tab.id ? styles.active : ''}`}
            onClick={() => setActiveTab(tab.id)}
          >
            {tab.label}
          </button>
        ))}
      </div>

      <ActiveComponent formState={formState} setFormState={setFormState} />

      <div className={styles['config-editor-actions']}>
        <button className={styles['btn-primary']} onClick={handleExport}>
          Export Configuration
        </button>
        <button className={styles['btn-secondary']} onClick={handleReset}>
          Reset to Saved
        </button>
      </div>

      {showExport && (
        <ExportModal
          configContent={configToJsContent(generateConfigFromState(formState))}
          onClose={() => setShowExport(false)}
          onDownload={handleDownload}
          onCopy={handleCopy}
        />
      )}
    </div>
  );
}
