/**
 * @file Config Editor Component
 * @description GUI-based configuration editor for local development only
 */

import React, { useState, useEffect, useCallback } from 'react';
import PropTypes from 'prop-types';
import styles from './configEditor.module.css';
import { hasConfigAccess } from '../../util/isLocal';
import config from '../../config';

/**
 * Parses GitHub username from URL
 * @param {string} url - GitHub URL
 * @returns {string} - Username or empty string
 */
function parseGithubUsername (url) {
  if (!url) return '';
  const match = url.match(/github\.com\/([^/]+)/);
  return match ? match[1] : '';
}

/**
 * Escapes single quotes in a string for use in single-quoted JavaScript strings
 * @param {string} str - String to escape
 * @returns {string} - Escaped string
 */
export function escapeString (str) {
  if (typeof str !== 'string') return str;
  // Escape single quotes and backslashes
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

/**
 * Formats an object for config output with proper indentation
 * @param {Object} obj - Object to format
 * @param {number} baseIndent - Base indentation level (spaces)
 * @returns {string} - Formatted string
 */
export function formatObject (obj, baseIndent = 2) {
  // Get the JSON representation
  const jsonStr = JSON.stringify(obj, null, 2)
    .replace(/"([^"]+)":/g, '$1:')
    .replace(/"/g, "'");

  const lines = jsonStr.split('\n');
  const baseSpaces = ' '.repeat(baseIndent);

  // First line is opening brace, subsequent lines need baseIndent added
  // but we need to preserve the relative indentation of nested content
  return lines
    .map((line, index) => {
      if (index === 0) {
        // Opening brace stays as is
        return line;
      }
      // For all other lines, add baseIndent spaces
      // The line already has its own indentation from JSON.stringify (2 spaces per level)
      // We need to add baseIndent to get the correct absolute position
      return baseSpaces + line;
    })
    .join('\n');
}

/**
 * Converts config object to JavaScript file content
 * @param {Object} configObj - Config object
 * @returns {string} - JavaScript file content
 */
export function configToJsContent (configObj) {
  const headersStr = formatObject(configObj.headers, 2);
  const linkStyleStr = formatObject(configObj.markdown.linkStyle, 4);
  const colorsStr = formatObject(configObj.colors, 2);

  return `/**
 * @author ${escapeString(configObj.name)}
 * @email ${escapeString(configObj.email)}
 * @create date ${new Date().toISOString().split('T')[0]}
 * @modify date ${new Date().toISOString().split('T')[0]}
 * @desc Blog Configuration - Generated by GUI Config Editor
 */
const config = {
  debug: ${configObj.debug},
  // github readme url
  readmeUrl: '${escapeString(configObj.readmeUrl)}',
  // blog title, on left top of the page
  title: '${escapeString(configObj.title)}',
  // author name
  name: '${escapeString(configObj.name)}',
  // social links, on bottom of the page
  social: {
    github: '${escapeString(configObj.social.github)}',
    linkedin: '${escapeString(configObj.social.linkedin)}'
  },
  email: '${escapeString(configObj.email)}',
  repo: '${escapeString(configObj.repo)}',
  resume_url: '${escapeString(configObj.resume_url)}',
  // default content shown on the main page, /src/articles/[config.default].md
  default: '${escapeString(configObj.default)}',
  headers: ${headersStr},
  // markdown settings
  markdown: {
    // set it false to disable markdown editor
    enable: ${configObj.markdown.enable},
    // set it true to enable loading animation in refreshing markdown preview.
    loading: ${configObj.markdown.loading},
    // delay time for refreshing markdown preview
    renderDelay: ${configObj.markdown.renderDelay},
    // tab size for markdown editor
    tabSize: ${configObj.markdown.tabSize},
    // the links in markdown does not have underlines, set it true to enable underline
    linkStyle: ${linkStyleStr}
  },
  themeChange: ${configObj.themeChange},
  colors: ${colorsStr}
}

export default config;
`;
}

/**
 * Initializes form state from existing config
 * @returns {Object} - Initial form state
 */
function getInitialFormState () {
  const githubUsername = parseGithubUsername(config.social?.github);

  // Preserve the actual headers array structure with all properties (type, customUrl)
  const headers = config.headers?.map(h => ({ ...h })) || [];

  return {
    blogTitle: config.title || '',
    authorName: config.name || '',
    email: config.email || '',
    githubUsername,
    linkedinUrl: config.social?.linkedin || '',
    repoUrl: config.repo || '',
    resumeUrl: config.resume_url || '',
    debug: config.debug || false,
    themeChange: config.themeChange !== false,
    // Preserve full headers array with type, customUrl, etc.
    headers,
    markdownEnable: config.markdown?.enable !== false,
    markdownLoading: config.markdown?.loading || false,
    markdownRenderDelay: config.markdown?.renderDelay || 0,
    markdownTabSize: config.markdown?.tabSize || 2,
    markdownLinkUnderline: config.markdown?.linkStyle?.textDecoration === 'underline',
    markdownLinkColor: config.markdown?.linkStyle?.color || '#0077ff'
  };
}

/**
 * Generates config object from form state
 * Preserves all header properties including type and customUrl
 * @param {Object} formState - Current form state
 * @returns {Object} - Config object
 */
export function generateConfigFromState (formState) {
  const githubUrl = formState.githubUsername
    ? `https://github.com/${formState.githubUsername}`
    : '';

  return {
    debug: formState.debug,
    readmeUrl: formState.repoUrl ? `${formState.repoUrl}/blob/main/README.md` : '',
    title: formState.blogTitle,
    name: formState.authorName,
    social: {
      github: githubUrl,
      linkedin: formState.linkedinUrl
    },
    email: formState.email,
    repo: formState.repoUrl,
    resume_url: formState.resumeUrl,
    default: formState.headers[0]?.title || 'About',
    headers: formState.headers,
    markdown: {
      enable: formState.markdownEnable,
      loading: formState.markdownLoading,
      renderDelay: parseInt(formState.markdownRenderDelay, 10) || 0,
      tabSize: parseInt(formState.markdownTabSize, 10) || 2,
      linkStyle: {
        textDecoration: formState.markdownLinkUnderline ? 'underline' : 'none',
        color: formState.markdownLinkColor
      }
    },
    themeChange: formState.themeChange,
    // Include colors from original config (preserved for components that use them)
    colors: config.colors || {
      light: { background: '#ffffff', foreground: '#feb272', gray: '#212529' },
      dark: { background: '#212020', foreground: '#653208', gray: '#a9a9b3' }
    }
  };
}

// Tab components
const TabGeneral = ({ formState, setFormState }) => (
  <div className={styles['tab-content']}>
    <h2>General Settings</h2>

    <div className={styles['form-group']}>
      <label htmlFor="blogTitle">Blog Title *</label>
      <input
        type="text"
        id="blogTitle"
        value={formState.blogTitle}
        onChange={(e) => setFormState(prev => ({ ...prev, blogTitle: e.target.value }))}
        placeholder="My Awesome Blog"
        required
      />
      <small>Displayed in the header and browser tab</small>
    </div>

    <div className={styles['form-group']}>
      <label htmlFor="authorName">Author Name *</label>
      <input
        type="text"
        id="authorName"
        value={formState.authorName}
        onChange={(e) => setFormState(prev => ({ ...prev, authorName: e.target.value }))}
        placeholder="John Doe"
        required
      />
    </div>

    <div className={styles['form-group']}>
      <label htmlFor="email">Email Address</label>
      <input
        type="email"
        id="email"
        value={formState.email}
        onChange={(e) => setFormState(prev => ({ ...prev, email: e.target.value }))}
        placeholder="john@example.com"
      />
    </div>

    <div className={styles['form-group']}>
      <label htmlFor="repoUrl">GitHub Repository URL</label>
      <input
        type="url"
        id="repoUrl"
        value={formState.repoUrl}
        onChange={(e) => setFormState(prev => ({ ...prev, repoUrl: e.target.value }))}
        placeholder="https://github.com/username/repo"
      />
      <small>Used to generate README and issue links</small>
    </div>
  </div>
);

const TabSocial = ({ formState, setFormState }) => (
  <div className={styles['tab-content']}>
    <h2>Social Links</h2>

    <div className={styles['form-group']}>
      <label htmlFor="githubUsername">GitHub Username</label>
      <input
        type="text"
        id="githubUsername"
        value={formState.githubUsername}
        onChange={(e) => setFormState(prev => ({ ...prev, githubUsername: e.target.value }))}
        placeholder="username"
      />
    </div>

    <div className={styles['form-group']}>
      <label htmlFor="linkedinUrl">LinkedIn URL</label>
      <input
        type="url"
        id="linkedinUrl"
        value={formState.linkedinUrl}
        onChange={(e) => setFormState(prev => ({ ...prev, linkedinUrl: e.target.value }))}
        placeholder="https://linkedin.com/in/username"
      />
    </div>

    <div className={styles['form-group']}>
      <label htmlFor="resumeUrl">Resume/CV URL</label>
      <input
        type="url"
        id="resumeUrl"
        value={formState.resumeUrl}
        onChange={(e) => setFormState(prev => ({ ...prev, resumeUrl: e.target.value }))}
        placeholder="https://example.com/resume.pdf"
      />
      <small>External link to your resume (opens in new tab)</small>
    </div>
  </div>
);

const TabHeaders = ({ formState, setFormState }) => {
  const [newHeader, setNewHeader] = useState({ title: '', type: 'article', customUrl: '' });
  const [editingIndex, setEditingIndex] = useState(null);
  const [editHeader, setEditHeader] = useState({ title: '', type: 'article', customUrl: '' });

  const addHeader = () => {
    if (!newHeader.title.trim()) return;
    const header = {
      title: newHeader.title.trim(),
      type: newHeader.type
    };
    if (newHeader.customUrl.trim()) {
      header.customUrl = newHeader.customUrl.trim();
    }
    setFormState(prev => ({
      ...prev,
      headers: [...prev.headers, header]
    }));
    setNewHeader({ title: '', type: 'article', customUrl: '' });
  };

  const removeHeader = (index) => {
    setFormState(prev => ({
      ...prev,
      headers: prev.headers.filter((_, i) => i !== index)
    }));
  };

  const moveHeader = (index, direction) => {
    const newHeaders = [...formState.headers];
    if (direction === 'up' && index > 0) {
      [newHeaders[index], newHeaders[index - 1]] = [newHeaders[index - 1], newHeaders[index]];
    } else if (direction === 'down' && index < newHeaders.length - 1) {
      [newHeaders[index], newHeaders[index + 1]] = [newHeaders[index + 1], newHeaders[index]];
    }
    setFormState(prev => ({ ...prev, headers: newHeaders }));
  };

  const startEdit = (index) => {
    setEditingIndex(index);
    setEditHeader({ ...formState.headers[index] });
  };

  const saveEdit = () => {
    if (!editHeader.title.trim()) return;
    const updated = { title: editHeader.title.trim(), type: editHeader.type };
    if (editHeader.customUrl?.trim()) {
      updated.customUrl = editHeader.customUrl.trim();
    }
    const newHeaders = [...formState.headers];
    newHeaders[editingIndex] = updated;
    setFormState(prev => ({ ...prev, headers: newHeaders }));
    setEditingIndex(null);
  };

  const cancelEdit = () => {
    setEditingIndex(null);
    setEditHeader({ title: '', type: 'article', customUrl: '' });
  };

  return (
    <div className={styles['tab-content']}>
      <h2>Navigation Headers</h2>
      <p>Configure the navigation menu items. Each header represents a page or link in your blog.</p>

      <div className={styles['help-section']} data-testid="headers-help-section">
        <h4>How Headers Work</h4>
        <ul>
          <li><strong>Article headers</strong> load markdown files from <code>src/articles/</code></li>
          <li><strong>Link headers</strong> open external URLs in a new tab</li>
          <li><strong>Custom URL</strong> (optional) specifies a custom path for article headers</li>
          <li>The first header becomes your default/home page</li>
        </ul>

        <h4>Creating Articles</h4>
        <p>For each <strong>article</strong> header, create a markdown file in <code>src/articles/</code>:</p>
        <ul>
          <li>Header &quot;About&quot; (no customUrl) → create <code>src/articles/About.md</code></li>
          <li>Header &quot;Projects&quot; with customUrl &quot;Projects/mobile_app&quot; → create <code>src/articles/Projects/mobile_app.md</code></li>
          <li>Header &quot;Work&quot; with customUrl &quot;Work/Experience&quot; → create <code>src/articles/Work/Experience.md</code></li>
        </ul>
      </div>

      <div className={styles['headers-list']}>
        {formState.headers.map((header, index) => (
          <div key={index} className={styles['header-item']}>
            {
              editingIndex === index
                ? (
                  <div className={styles['header-edit-form']}>
                    <div className={styles['form-row']}>
                      <input
                        type="text"
                        value={editHeader.title}
                        onChange={(e) => setEditHeader(prev => ({ ...prev, title: e.target.value }))}
                        placeholder="Title"
                      />
                      <select
                        value={editHeader.type}
                        onChange={(e) => setEditHeader(prev => ({ ...prev, type: e.target.value }))}
                      >
                        <option value="article">Article</option>
                        <option value="link">External Link</option>
                      </select>
                    </div>
                    <input
                      type="text"
                      value={editHeader.customUrl || ''}
                      onChange={(e) => setEditHeader(prev => ({ ...prev, customUrl: e.target.value }))}
                      placeholder={editHeader.type === 'article' ? 'Custom path (optional, e.g., Projects/Project)' : 'Full URL (https://...)'}
                    />
                    <div className={styles['header-actions']}>
                      <button onClick={saveEdit} className={styles['btn-small-primary']}>Save</button>
                      <button onClick={cancelEdit} className={styles['btn-small-secondary']}>Cancel</button>
                    </div>
                  </div>
                  )
                : (
                  <>
                    <div className={styles['header-info']}>
                      <span className={styles['header-title']}>{header.title}</span>
                      <span className={styles['header-type']}>{header.type}</span>
                      {
                        header.customUrl
                          ? (
                            <span className={styles['header-custom-url']}>({header.customUrl})</span>
                            )
                          : null
                      }
                    </div>
                    <div className={styles['header-actions']}>
                      <button onClick={() => moveHeader(index, 'up')} disabled={index === 0}>↑</button>
                      <button onClick={() => moveHeader(index, 'down')} disabled={index === formState.headers.length - 1}>↓</button>
                      <button onClick={() => startEdit(index)} className={styles['btn-small-secondary']}>Edit</button>
                      <button onClick={() => removeHeader(index)} className={styles['btn-small-danger']}>Remove</button>
                    </div>
                  </>
                  )
            }
          </div>
        ))}
      </div>

      <div className={styles['add-header-form']} data-testid="add-header-form">
        <h4>Add New Header</h4>
        <div className={styles['form-row']}>
          <input
            type="text"
            value={newHeader.title}
            onChange={(e) => setNewHeader(prev => ({ ...prev, title: e.target.value }))}
            placeholder="Header title (e.g., Projects)"
            data-testid="new-header-title"
          />
          <select
            value={newHeader.type}
            onChange={(e) => setNewHeader(prev => ({ ...prev, type: e.target.value }))}
            data-testid="new-header-type"
          >
            <option value="article">Article</option>
            <option value="link">External Link</option>
          </select>
        </div>
        <input
          type="text"
          value={newHeader.customUrl}
          onChange={(e) => setNewHeader(prev => ({ ...prev, customUrl: e.target.value }))}
          placeholder={newHeader.type === 'article' ? 'Custom path (optional, e.g., Projects/Project)' : 'Full URL (https://...)'}
          data-testid="new-header-customurl"
        />
        <button onClick={addHeader} className={styles['btn-secondary']} data-testid="add-header-button">
          Add Header
        </button>
      </div>
    </div>
  );
};

const TabSettings = ({ formState, setFormState }) => (
  <div className={styles['tab-content']}>
    <h2>Settings</h2>

    <div className={styles['form-group']}>
      <div className={styles['checkbox-group']}>
        <label>
          <input
            type="checkbox"
            checked={formState.themeChange}
            onChange={() => setFormState(prev => ({ ...prev, themeChange: !prev.themeChange }))}
          />
          Enable Theme Switcher (Light/Dark mode toggle)
        </label>
      </div>
    </div>

    <div className={styles['form-group']}>
      <div className={styles['checkbox-group']}>
        <label>
          <input
            type="checkbox"
            checked={formState.debug}
            onChange={() => setFormState(prev => ({ ...prev, debug: !prev.debug }))}
          />
          Enable Debug Mode
        </label>
        <small>Shows debug messages in browser console</small>
      </div>
    </div>

    <div className={styles['form-group']}>
      <div className={styles['checkbox-group']}>
        <label>
          <input
            type="checkbox"
            checked={formState.markdownEnable}
            onChange={() => setFormState(prev => ({ ...prev, markdownEnable: !prev.markdownEnable }))}
          />
          Enable Markdown Editor (adds /?page=markdown route)
        </label>
      </div>
    </div>

    <h3>Markdown Editor Settings</h3>

    <div className={styles['form-group']}>
      <label htmlFor="markdownTabSize">Tab Size</label>
      <input
        type="number"
        id="markdownTabSize"
        value={formState.markdownTabSize}
        onChange={(e) => setFormState(prev => ({ ...prev, markdownTabSize: e.target.value }))}
        min="1"
        max="8"
      />
    </div>

    <div className={styles['form-group']}>
      <div className={styles['checkbox-group']}>
        <label>
          <input
            type="checkbox"
            checked={formState.markdownLinkUnderline}
            onChange={() => setFormState(prev => ({ ...prev, markdownLinkUnderline: !prev.markdownLinkUnderline }))}
          />
          Underline Links in Markdown Preview
        </label>
      </div>
    </div>

    <div className={styles['form-group']}>
      <label htmlFor="markdownLinkColor">Link Color</label>
      <input
        type="color"
        id="markdownLinkColor"
        value={formState.markdownLinkColor}
        onChange={(e) => setFormState(prev => ({ ...prev, markdownLinkColor: e.target.value }))}
      />
    </div>
  </div>
);

TabGeneral.propTypes = {
  formState: PropTypes.object.isRequired,
  setFormState: PropTypes.func.isRequired
};

TabSocial.propTypes = {
  formState: PropTypes.object.isRequired,
  setFormState: PropTypes.func.isRequired
};

TabHeaders.propTypes = {
  formState: PropTypes.object.isRequired,
  setFormState: PropTypes.func.isRequired
};

TabSettings.propTypes = {
  formState: PropTypes.object.isRequired,
  setFormState: PropTypes.func.isRequired
};

// Export Modal Component
function ExportModal ({ configContent, onClose, onDownload, onCopy }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    onCopy();
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className={styles.modal} onClick={onClose} data-testid="export-modal">
      <div className={styles['modal-content']} onClick={(e) => e.stopPropagation()}>
        <div className={styles['modal-header']}>
          <h2>Export Configuration</h2>
          <button className={styles['modal-close']} onClick={onClose} data-testid="modal-close">
            &times;
          </button>
        </div>
        <div className={styles['modal-body']}>
          <div className={styles['export-info']} data-testid="export-info">
            <p><strong>After exporting:</strong></p>
            <ol>
              <li>Copy the config below or download the file</li>
              <li>Replace <code>src/config.js</code> with the new content</li>
              <li>Create markdown files in <code>src/articles/</code> for each article header:</li>
            </ol>
            <ul>
              <li>Header &quot;About&quot; → <code>src/articles/About.md</code></li>
              <li>Header &quot;Work&quot; with customUrl &quot;Work/Experience&quot; → <code>src/articles/Work/Experience.md</code></li>
            </ul>
          </div>
          <div className={styles['export-actions']}>
            <button className={styles['btn-primary']} onClick={onDownload}>
              Download config.js
            </button>
            <button className={styles['btn-secondary']} onClick={handleCopy}>
              {copied ? 'Copied!' : 'Copy to Clipboard'}
            </button>
          </div>
          <div className={styles['export-preview']}>
            <code>
              <pre>{configContent}</pre>
            </code>
          </div>
        </div>
      </div>
    </div>
  );
}

ExportModal.propTypes = {
  configContent: PropTypes.string.isRequired,
  onClose: PropTypes.func.isRequired,
  onDownload: PropTypes.func.isRequired,
  onCopy: PropTypes.func.isRequired
};

// Main Config Editor Component
export default function ConfigEditor () {
  const [hasAccess, setHasAccess] = useState(null);
  const [activeTab, setActiveTab] = useState('general');
  const [formState, setFormState] = useState(getInitialFormState());
  const [showExport, setShowExport] = useState(false);

  useEffect(() => {
    setHasAccess(hasConfigAccess());
  }, []);

  const handleExport = useCallback(() => {
    setShowExport(true);
  }, []);

  const handleDownload = useCallback(() => {
    const newConfig = generateConfigFromState(formState);
    const content = configToJsContent(newConfig);
    const blob = new Blob([content], { type: 'application/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'config.js';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [formState]);

  const handleCopy = useCallback(() => {
    const newConfig = generateConfigFromState(formState);
    const content = configToJsContent(newConfig);
    navigator.clipboard.writeText(content);
  }, [formState]);

  const handleReset = useCallback(() => {
    if (window.confirm('Reset all settings to current saved values?')) {
      setFormState(getInitialFormState());
    }
  }, []);

  if (hasAccess === null) {
    return (
      <div className={styles.loading} data-testid="config-loading">
        <p>Checking access...</p>
      </div>
    );
  }

  if (!hasAccess) {
    return (
      <div className={styles['access-denied']} data-testid="access-denied">
        <div className={styles['access-denied-content']}>
          <h1>Access Denied</h1>
          <p>
            The configuration editor is only accessible from a local development environment.
          </p>
          <code className={styles['access-hint']}>npm start</code>
          <p className={styles['access-note']}>
            Visitors to your published blog cannot access this page.
          </p>
        </div>
      </div>
    );
  }

  const tabs = [
    { id: 'general', label: 'General', component: TabGeneral },
    { id: 'social', label: 'Social', component: TabSocial },
    { id: 'headers', label: 'Headers', component: TabHeaders },
    { id: 'settings', label: 'Settings', component: TabSettings }
  ];

  const ActiveComponent = tabs.find(t => t.id === activeTab)?.component || TabGeneral;

  return (
    <div className={styles['config-editor-container']} data-testid="config-editor-container">
      <div className={styles['config-editor-header']}>
        <h1>Blog Configuration</h1>
        <p>Edit your blog settings. Changes will be exported as a config.js file.</p>
      </div>

      <div className={styles['config-editor-tabs']}>
        {tabs.map(tab => (
          <button
            key={tab.id}
            className={`${styles.tab} ${activeTab === tab.id ? styles.active : ''}`}
            onClick={() => setActiveTab(tab.id)}
          >
            {tab.label}
          </button>
        ))}
      </div>

      <ActiveComponent formState={formState} setFormState={setFormState} />

      <div className={styles['config-editor-actions']}>
        <button className={styles['btn-primary']} onClick={handleExport}>
          Export Configuration
        </button>
        <button className={styles['btn-secondary']} onClick={handleReset}>
          Reset to Saved
        </button>
      </div>

      {showExport && (
        <ExportModal
          configContent={configToJsContent(generateConfigFromState(formState))}
          onClose={() => setShowExport(false)}
          onDownload={handleDownload}
          onCopy={handleCopy}
        />
      )}
    </div>
  );
}
