'use strict';

// About and Work share their facts with the personal agent. Edit profile.json.
const fs = require('fs');
const path = require('path');
const profile = require('../src/data/profile.json');
const root = path.resolve(__dirname, '../src/articles');
const link = page => `/?page=${encodeURIComponent(page)}`;
const engineering = profile.highlights.filter(item => item.kind === 'engineering');
const research = profile.highlights.filter(item => item.kind === 'research');
const writingTitles = {
  'Blogs/AI/My_AI_Research_and_Engineering_Journey': 'From Deep Learning to Production AI Agents',
  'Blogs/DeepLearning/Civilization_Intelligence': 'Civilizational Intelligence'
};
const compact = item => `### [${item.name}](/?page=Work#${item.id})\n\n*${item.label}*\n\n${item.summary}`;
const detail = item => `<section id="${item.id}">\n\n### ${item.name}\n\n*${item.label}*\n\n**Problem.** ${item.problem}\n\n**${item.kind === 'research' ? 'Research' : 'My work'}.** ${item.contribution}\n\n**Approach.** ${item.approach}\n\n[${item.kind === 'research' ? 'Read the paper' : 'Read the project background'}](${item.kind === 'research' ? item.url : link(item.source)})\n\n</section>`;
const about = `<!-- Generated by scripts/generate-profile.js from src/data/profile.json -->
<div class="profile-hero">
<p class="eyebrow">${profile.name} / ${profile.alias} · ${profile.role}</p>

# ${profile.headline}

${profile.intro}

<nav class="profile-actions" aria-label="Explore my work"><a href="/?page=Work">Work & research ↗</a><a href="${profile.contact.resume}">My résumé ↗</a></nav>
</div>

${profile.summary}

## Building agents

### [${profile.current.project} · ${profile.current.organization}](/?page=Work#nova-agent)

${profile.current.summary}

${profile.current.detail}

${compact(engineering.find(item => item.id === 'tiktok-coding-agent'))}

## Selected research

${research.map(compact).join('\n\n')}

## Product experiments

I also build products to explore how people interact with AI: [AgentShelf](https://github.com/tempest2023/AgentShelf), a hackathon prototype for AI commerce readiness; [Obi](https://github.com/tempest2023/Obi), a frontend for a general-agent product; and [Live Subtitles](https://github.com/tempest2023/live-subtitles), an app for streaming speech transcription and translation.

[Explore selected projects](/?page=Projects/Project)

## How the work connects

My engineering work asks how agents can complete useful tasks with tools, documents, and human review. My research asks how models can make precise changes and generate outputs that respect structure. Evaluation connects the two: the output has to hold up in the workflow where it will be used.

Earlier work at Ant Group, Ansys, and Pittsburgh gave me experience with production services, mobile applications, and research software. That engineering foundation shapes how I build AI systems today.

[My research and engineering journey](${link(profile.featuredWriting[0])}) · [Technical background](/?page=TechStack)

## Writing

${profile.featuredWriting.map(page => `- [${writingTitles[page]}](${link(page)})`).join('\n')}

[Browse all writing](/?page=Blog)

## Let's connect

For research, agent engineering, and collaboration, [email me](mailto:${profile.contact.email}) or find me on [GitHub](${profile.contact.github}) and [LinkedIn](${profile.contact.linkedin}).
`;
const work = `<!-- Generated by scripts/generate-profile.js from src/data/profile.json -->
# Work & Research

I build agents for complex workflows and co-author research on structured generation, precise editing, and tool use. Here are the problems, approaches, and public sources behind that work.

## Agent engineering

${engineering.map(detail).join('\n\n')}

## Selected research

${research.map(detail).join('\n\n')}

## Earlier research

${profile.research.map(item => `### [${item.name}](${item.url})\n\n${item.summary}`).join('\n\n')}

## Experience

${profile.experience.map(item => `### ${item.organization}\n\n*${item.period}*\n\n${item.summary}`).join('\n\n')}

## Education

${profile.education.map(item => `- **${item.institution}** — ${item.degree}, ${item.period}`).join('\n')}

[Complete résumé](${profile.contact.resume}) · [Selected projects](/?page=Projects/Project) · [Contact Tao](mailto:${profile.contact.email})
`;
fs.writeFileSync(path.join(root, 'About.md'), about);
fs.writeFileSync(path.join(root, 'Work.md'), work);
console.log('Generated About and Work from the public profile.');
