'use strict';

// These pages share their facts with the personal agent. Edit profile.json.
const fs = require('fs');
const path = require('path');
const profile = require('../src/data/profile.json');
const root = path.resolve(__dirname, '../src/articles');
const link = (page) => `/?page=${encodeURIComponent(page)}`;
const about = `<!-- Generated by scripts/generate-profile.js from src/data/profile.json -->
<div class="profile-hero">
<p class="eyebrow">${profile.name} / ${profile.alias} · ${profile.role}</p>

# ${profile.headline}

${profile.intro}

${profile.summary}

<nav class="profile-actions" aria-label="Explore my work"><a class="primary-link" href="/?page=Work">Explore my work ↗</a><a href="${profile.contact.resume}">Read my résumé ↗</a><a href="mailto:${profile.contact.email}">Get in touch ↗</a></nav>
</div>

## Currently building

### ${profile.current.project} · ${profile.current.organization}

${profile.current.summary}

${profile.current.detail}

## Selected work

${profile.highlights.slice(1).map(item => `### [${item.name}](${item.url})\n\n*${item.label}*\n\n${item.summary}`).join('\n\n')}

[Explore all work and research](/?page=Work)

## A path through research and engineering

I began experimenting with deep learning applications in 2014. At SUSTech, work on GAN-based face generation and web accessibility introduced me to research problems that combined models, formal structure, and practical engineering.

At Ant Group, I built software for financial workflows. At Pittsburgh, I worked alongside rehabilitation researchers on systems for studies and training programs. My TikTok work connected mobile engineering with LLM-based developer tools. Those experiences now inform how I build agents for insurance operations.

I have also built products from the ground up, including Tira AI and AgentShelf. Building for users keeps my research questions grounded: what needs to be evaluated, where does the workflow break, and what should remain under human control?

[Read my complete research and engineering journey](${link(profile.featuredWriting[0])}) · [View projects](/?page=Projects/Project)

## Questions I keep returning to

${profile.interests.map(item => `- ${item}`).join('\n')}

For me, useful intelligence includes the system around the model: tools, memory, evaluation, permissions, and runtime behavior. I am interested in how these pieces work together when documents are messy, tasks span many steps, and people need to inspect the result.

## Writing

- [From Deep Learning to Production AI Agents](${link(profile.featuredWriting[0])})
- [Civilizational Intelligence](${link(profile.featuredWriting[1])})
- [My Frontend Journey](${link(profile.featuredWriting[2])})

[Browse all writing](/?page=Blog) · [Technical background](/?page=TechStack)

## Let's connect

Interested in research, agent systems, or engineering collaboration? [Email me](mailto:${profile.contact.email}) or find me on [LinkedIn](${profile.contact.linkedin}) and [GitHub](${profile.contact.github}). For career opportunities and current availability, please contact me directly.
`;
const work = `<!-- Generated from src/data/profile.json -->
# Work & Research

Production systems and research exploring how models work with structure, tools, and real-world constraints.

${profile.highlights.map(item => `<section id="${item.id}">\n\n## ${item.name}\n\n*${item.label}*\n\n${item.summary}\n\n${item.contribution}\n\n[${item.url.startsWith('https:') ? 'Read the paper' : 'Read the background'}](${item.url.startsWith('https:') ? item.url : link(item.source)})\n\n</section>`).join('\n\n')}

## Further research

${profile.research.map(item => `### [${item.name}](${item.url})\n\n${item.summary}`).join('\n\n')}

## Experience

${profile.experience.map(item => `### ${item.organization}\n\n*${item.period}*\n\n${item.summary}`).join('\n\n')}

## Education

${profile.education.map(item => `- **${item.institution}** — ${item.degree}, ${item.period}`).join('\n')}

[Complete résumé](${profile.contact.resume}) · [Projects](/?page=Projects/Project) · [Contact Tao](mailto:${profile.contact.email})
`;
fs.writeFileSync(path.join(root, 'About.md'), about);
fs.writeFileSync(path.join(root, 'Work.md'), work);
console.log('Generated About and Work from the public profile.');
