/**
 * @author Tempest
 * @email tar118@pitt.edu
 * @create date 2026-02-14
 * @modify date 2026-02-14
 * @desc Blog Configuration - Generated by GUI Config Editor
 */
const config = {
  debug: false,
  // github readme url
  readmeUrl: 'https://github.com/tempest2023/ConciseMarkDownBlog/blob/main/README.md',
  // blog title, on left top of the page
  title: 'Tempest\'s Blog',
  // author name
  name: 'Tempest',
  // social links, on bottom of the page
  social: {
    github: 'https://github.com/tempest2023',
    linkedin: 'https://www.linkedin.com/in/taoren-pitt/'
  },
  email: 'tar118@pitt.edu',
  repo: 'https://github.com/tempest2023/ConciseMarkDownBlog',
  resume_url: '',
  // default content shown on the main page, /src/articles/[config.default].md
  default: 'About',
  headers: [
    {
      title: 'About',
      type: 'article'
    },
    {
      title: 'Tech Stack',
      type: 'article',
      customUrl: 'TechStack'
    },
    {
      title: 'Blog',
      type: 'article'
    },
    {
      title: 'Projects',
      type: 'article',
      customUrl: 'Projects/Project'
    },
    {
      title: 'MarkDown',
      type: 'article'
    },
    {
      title: 'Resume',
      type: 'link',
      customUrl: 'https://drive.google.com/file/d/1aNJ-NPuk71x4xQgRo5Es2WPyNZA8kbCb/view?usp=sharing'
    },
    {
      title: 'Links',
      type: 'article'
    }
  ],
  // markdown settings
  markdown: {
    // set it false to disable markdown editor
    enable: true,
    // set it true to enable loading animation in refreshing markdown preview.
    loading: false,
    // delay time for refreshing markdown preview
    renderDelay: 0,
    // tab size for markdown editor
    tabSize: 4,
    // the links in markdown does not have underlines, set it true to enable underline
    linkStyle: {
      textDecoration: 'none',
      color: '#0077ff'
    }
  },
  // show theme switch button in the header, default to true
  themeEnable: true,
  // show footer with social links and copyright, default to true
  footer: true,
  colors: {
    light: {
      background: '#ffffff',
      foreground: '#0077ff',
      gray: '#6c757d',
      text: '#212529',
      border: '#dee2e6',
      cardBg: '#f8f9fa'
    },
    dark: {
      background: '#212529',
      foreground: '#0d6efd',
      gray: '#adb5bd',
      text: '#f8f9fa',
      border: '#495057',
      cardBg: '#343a40'
    }
  }
}

export default config;
