/**
 * @author Tempest
 * @email tar118@pitt.edu
 * @create date 2026-02-14
 * @modify date 2026-05-13
 * @desc Blog Configuration - Generated by GUI Config Editor
 */
const config = {
  debug: false,
  // github readme url
  readmeUrl: 'https://github.com/tempest2023/ConciseMarkDownBlog/blob/main/README.md',
  // blog title, on left top of the page
  title: 'Tao Ren / Tempest',
  // author name
  name: 'Tempest',
  // social links, on bottom of the page
  social: {
    github: 'https://github.com/tempest2023',
    linkedin: 'https://www.linkedin.com/in/taoren-pitt/'
  },
  email: 'tar118@pitt.edu',
  repo: 'https://github.com/tempest2023/ConciseMarkDownBlog',
  resume_url: 'https://drive.google.com/file/d/1aNJ-NPuk71x4xQgRo5Es2WPyNZA8kbCb/view?usp=sharing',
  // default content shown on the main page, /src/articles/[config.default].md
  default: 'About',
  headers: [
    {
      title: 'About',
      type: 'article'
    },
    {
      title: 'Work & Research',
      type: 'article',
      customUrl: 'Work'
    },
    {
      title: 'Writing',
      type: 'article',
      customUrl: 'Blog'
    },
    {
      title: 'Projects',
      type: 'article',
      customUrl: 'Projects/Project'
    },
    {
      title: 'Ask Tempest',
      type: 'article',
      customUrl: 'Ask'
    }
  ],
  // markdown settings
  markdown: {
    // set it false to disable markdown editor
    enable: true,
    // set it true to enable loading animation in refreshing markdown preview.
    loading: false,
    // delay time for refreshing markdown preview
    renderDelay: 0,
    // tab size for markdown editor
    tabSize: 4,
    // the links in markdown does not have underlines, set it true to enable underline
    linkStyle: {
      textDecoration: 'underline',
      color: 'var(--link-color, #174bb8)'
    }
  },
  // show theme switch button in the header, default to true
  themeEnable: true,
  // show footer with social links and copyright, default to true
  footer: true,
  colors: {
    light: {
      background: '#fcfcfa',
      foreground: '#174bb8',
      gray: '#6c757d',
      text: '#212529',
      border: '#dee2e6',
      cardBg: '#f8f9fa'
    },
    dark: {
      background: '#212529',
      foreground: '#93b9ff',
      gray: '#adb5bd',
      text: '#f8f9fa',
      border: '#495057',
      cardBg: '#343a40'
    }
  }
}

export default config;
